version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      order-service:
        condition: service_healthy
      payments-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PAYMENTS_SERVICE_URL: http://payments-service:9090
      ORDER_SERVICE_URL: http://order-service:9091
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 90s

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "9091:9091"
    depends_on:
      order-service-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order-service
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 90s

  payments-service:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    container_name: payments-service
    ports:
      - "9090:9090"
    depends_on:
      payments-service-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/payments-service
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 90s


  order-service-db:
    image: postgres:15.15
    container_name: order-service-db
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gozon -d gozon"]
      interval: 10s
      timeout: 5s
      retries: 5

  payments-service-db:
    image: postgres:15.15
    container_name: payments-service-db
    environment:
      POSTGRES_DB: payments-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gozon -d gozon"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: gozon-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        kafka-topics --create --topic gozon.orders.v1 --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 &&
        kafka-topics --create --topic gozon.payments.v1 --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 &&
        echo 'Топики созданы!' &&
        kafka-topics --list --bootstrap-server kafka:9092
      "

volumes:
  postgres_data: