spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: false
  kafka:
    consumer:
      enable-auto-commit: false
      auto-offset-reset: false
    bootstrap-servers: localhost:9092
    topics:
      gozon:
        orders:
          v1: gozon.orders.v1
        payments:
          v1: gozon.payments.v1
  datasource:
    url: jdbc:postgresql://postgres:5433/payments-service
    username: user
    password: 123

server:
  port: 9090